{% set name = "eight" %}
{% set version = "1.0.1" %}
{% set sha256 = "6465970d3c12a1d759151690629b10b50ffb124c9b62e912999ee9233378a562" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.3
    - setuptools
    - future
  run:
    - python >=3.3
    - future

test:
  imports:
    - eight

about:
  home: https://github.com/kislyuk/eight
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Eight is a Python module that provides a minimalist compatibility layer between Python 3 and 2'
  description: |
    Eight is inspired by six, nine, and python-future, but provides better
    internationalization (i18n) support, is more lightweight, easier to use,
    and unambiguously biased toward Python 3 code: if you remove eight from
    your code, it will continue to function exactly as it did with eight on
    Python 3.
  doc_url: https://eight.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/eight

extra:
  recipe-maintainers:
    - cmutel
