{% set name = "eight" %}
{% set version = "0.4.2" %}
{% set sha256 = "eebadb79193c9a3ed95a74f59462267f05ca41c23a804f9f0dd80e597c9a9f8e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future
  run:
    - python
    - future

test:
  imports:
    - eight

about:
  home: https://github.com/kislyuk/eight
  license: Apache-2.0
  summary: 'Eight is a Python module that provides a minimalist compatibility layer between Python 3 and 2'
  description: |
    Eight is inspired by six, nine, and python-future, but provides better
    internationalization (i18n) support, is more lightweight, easier to use,
    and unambiguously biased toward Python 3 code: if you remove eight from
    your code, it will continue to function exactly as it did with eight on
    Python 3.
  doc_url: https://eight.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/eight

extra:
  recipe-maintainers:
    - cmutel
