travis:
  secure:
    BINSTAR_TOKEN: WLJUgYoIXycCTFcuQTH8VoZi9LH1Mo+Uw+3VVQjAVzWdkQ2B7AEOhnLz8lbfFdkNqmNlrxZjkSK4d5gpYN3cS6j+4p+P5VqxSesbuLZH9ipStPwQIm6xTR4B9yqbeLscP4TDhECW0MV8LM+tgSkqNNrvTw95JWyNRR92NMCRTBMjDusKD8RG36WFPXMVXlG8q/73oqQLtgSnJIArwyr/dbxiM1BTLzOSxFKI6aQcndOgKfyeDHLsFpuN7R5+lgyM9Iwg4H5nr7KFbFqK+aSJ3wBmFMiZKljKatqNLIoiPDVmLCZWzbDqaww1OIMjzhESYJs7l1bGKCFPRSJ0lWetPMWQiE6ufHyHV0lhWJ1kNgLJl3sHIyxg9NfL6llcDf4kfCdDRHQphKBeKCbuRaq1lpvneyUAdnAU0Aq1zyy/EiZjWIOocxjZB3aq4q/q3J56ATVM7yrnp1s1yMEW0iM4banhGapEyz3DOU0QucnygLecpVDBHE26bmH9Y/6/+errD0FNeaPoxYkBuO0Nx31Zm09tzNQCt9bwspmc8zHOyvUmVYrVq9kSealSQHH2ZZB3Of1F/qQJBAMvqeJoI1qUhv6izSL0zctlJv4hJHyiGQVOviddfDAz2apKjwh+rMArbz6zSV+alqEibErstNOxRzVkthGa3p1h77qt93u0n+c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
